import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className='py-0 px-8'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='min-h-screen py-16 flex-1 flex flex-col justify-center items-center'>
        <h1 className='m-0 leading-[1.15rem] text-[4rem] text-center'>
          Welcome to{' '}
          <a
            href='https://nextjs.org'
            className='text-[#0070f3] hover:underline focus:underline active:underline'
          >
            Next.js!
          </a>
        </h1>

        <p className='my-16 mx-0 leading-6 text-2xl'>
          Get started by editing{' '}
          <code className='bg-[#fafafa] rounded-[5px] p-3 text-[1.1rem] font-menlo dark:bg-[#111]'>
            pages/index.js
          </code>
        </p>

        <div className='flex items-center justify-center flex-wrap max-w-[800px] maxSm:w-full maxSm:flex-col'>
          <a
            href='https://nextjs.org/docs'
            className='m-4 p-6 text-left text-inherit border border-[#eaeaea] rounded-[10px] transition max-w-[300px] hover:border-[#0070f3] focus:border-[#0070f3] active:border-[#0070f3] dark:border-[#222]'
          >
            <h2 className='mb-4 m-0 text-2xl'>Documentation &rarr;</h2>
            <p className='m-0 text-xl leading-6'>
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a
            href='https://nextjs.org/learn'
            className='m-4 p-6 text-left text-inherit border border-[#eaeaea] rounded-[10px] transition max-w-[300px] hover:border-[#0070f3] focus:border-[#0070f3] active:border-[#0070f3] dark:border-[#222]'
          >
            <h2 className='mb-4 m-0 text-2xl'>Learn &rarr;</h2>
            <p className='m-0 text-xl leading-6'>
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/canary/examples'
            className='m-4 p-6 text-left text-inherit border border-[#eaeaea] rounded-[10px] transition max-w-[300px] hover:border-[#0070f3] focus:border-[#0070f3] active:border-[#0070f3] dark:border-[#222]'
          >
            <h2 className='mb-4 m-0 text-2xl'>Examples &rarr;</h2>
            <p className='m-0 text-xl leading-6'>
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className='m-4 p-6 text-left text-inherit border border-[#eaeaea] rounded-[10px] transition max-w-[300px] hover:border-[#0070f3] focus:border-[#0070f3] active:border-[#0070f3] dark:border-[#222]'
          >
            <h2 className='mb-4 m-0 text-2xl'>Deploy &rarr;</h2>
            <p className='m-0 text-xl leading-6'>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className='flex justify-center items-center flex-1 py-2 px-0 border-t-[1px] border-[#eaeaea] dark:border-[#222]'>
        <a
          className='flex justify-center items-center flex-grow'
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className='h-4 ml-2'>
            <Image
              src='/vercel.svg'
              alt='Vercel Logo'
              width={72}
              height={16}
              className='dark:invert'
            />
          </span>
        </a>
      </footer>
    </div>
  )
}
